services:
  - type: web
    name: CONTACT BOT
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/AJ_PYTHON/AJ_CONTACT
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK
        sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
